[package]
name = "flutter_tikz_rust_native"
version = "0.1.0"
edition = "2021"

[lib]
name = "flutter_tikz_rust_native"
crate-type = ["cdylib", "staticlib"]

[dependencies]
anyhow = "1.0.100"
dvi = "0.2.2"
dvi2html = "0.2.0"
flate2 = "1.0.34"
tar = "0.4.43"
wasmi = "0.39.0"
wat = "1.219.1"
